[package]
name = "rusty-os"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "0.9.8"
lazy_static = {version = "1.4.0", features = ["spin_no_std"]}
volatile = "0.2.6"
spin = "0.5.2"

[package.metadata.bootimage]
test-args = ["-device", "isa-debug-exit,iobase=0xf4,iosize=0x04"]